import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {signInWithGooglePopup, signInWithEmail, auth} from  "../config/firebase"
import { signInWithCustomToken } from "firebase/auth";
import { setDoc, doc, getDoc } from 'firebase/firestore'
import { db } from "../config/firebase"
import  { useState } from "react"
const Home: NextPage = () => {

  const timestamp: string = new Date().toLocaleTimeString();
  const [token, setToken] = useState<string>();
  const [values, setValues] = useState({
    email: '',
    password : ''
  })

  const handleInputs = (e:any) => {
    const {name, value} = e.target;
    setValues({
      ...values, 
      [name] : value
    })
  }
  const handleGoogleLogin = () => {
    signInWithGooglePopup().then(() => {
      alert("Login Successful");
    })
    .catch(e => {
      console.log("Error :", e);
    })
  }

  const handleData = async ()=> {
    const userDocRef = doc(db, "users",timestamp);
    setDoc(userDocRef,{
      name : "aman",
      age : 22,
      gender : "male",
      time : timestamp
    })
    const userSnapshot = await getDoc(userDocRef);
    console.log(userSnapshot);
  }

  const fetchData = async () => {
    const res = await fetch("api/customToken")
    .then((response) => response.json())
    .then((data) => {
      signInWithCustomToken(auth, data.token)
      .then((userCredential) => {
        alert("Login Successful");
      })
      .catch((error) => {
        console.log("Error while login with this token :",error)
      });
    })
    .catch(e => console.log("Error :", e))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>
        <div>
          <h2 style={{cursor : "pointer"}} onClick={handleGoogleLogin}>Google Login &rarr;</h2>
        </div>
        <div>
          <h2 style={{cursor : "pointer"}} onClick={handleData}>Push &rarr;</h2>
        </div>
        <div>
          <h2 style={{cursor : "pointer"}} onClick={fetchData}>Fetch &rarr;</h2>
        </div>
        <div>
          <input style={{padding : "10px 0px 10px 5px"}} type="text" name="email" placeholder="Email" onChange={handleInputs}/>
          <input style={{padding : "10px 0px 10px 5px"}} type="password" name="password" placeholder='Password' onChange={handleInputs}/>
          <button onClick={()=>signInWithEmail(values.email, values.password)} style={{padding : "10px 5px 10px 5px", cursor : "pointer"}}>Login</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
